### ISSUE TITLE
[Installation] Steps to install

### ISSUE THREAD

**Issue by panwarab** [ab-anand/Digital-Assistants#1]
Please mention the steps to install it on ubuntu

**Comment by ab-anand** [comment]
updated the readme. please check it out.

**Comment by ab-anand** [comment]
Also the locking and recycle bin feature won't work on Ubuntu

**Comment by vestronv** [comment]
Nope, not working in Ubuntu, atleast not in Python2.7. You are using winshell which requires `_winreg` which is windows registry access thus can't work with `winshell`, but it has been used in code(daily.py) and further more `espeak` not installing in Ubuntu

**Comment by ab-anand** [comment]
I've not tested it on ubuntu. I guess some features won't work in ubuntu.
